# CI de Nível 01 - Execução manual via botão

name: 'CI - Execução Manual com Relatório'

# Gatilho manual (workflow_dispatch)
on:
  workflow_dispatch:

jobs:
  unit-tests:
    name: 'Rodar testes unitários com Mocha'
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' 

      - name: Instalar dependências do projeto
        run: npm install

      - name: Executar testes com relatório
        run: npm run test:report

      - name: Upload do relatório mochawesome
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-mochawesome
          path: mochawesome-report